### ISSUE TITLE
[1.20.1 Forge] Text seems to be duplicated.

### ISSUE THREAD

**Issue by PlayfulPiano** [MattCzyr/ExplorersCompass#57] opened 2023-11-30 06:39 UTC
Forge: 47.2.8
Explorer's Compass: 1.3.3

![image](https://github.com/MattCzyr/ExplorersCompass/assets/3158887/9a1c09fd-d48b-4d0a-a205-970b4805a8a6)
Unsure what is causing this. Will post my latest.log as it should contain a modlist in case it might be a mod incompatibility issue.
[latest.log](https://github.com/MattCzyr/ExplorersCompass/files/13509335/latest.log)

**Comment by MattCzyr** [comment] 2023-12-06 23:48
This seems to be an issue caused by the Raised mod. See [Nature's Compass #168](https://github.com/MattCzyr/NaturesCompass/issues/168).

**Comment by PlayfulPiano** [comment] 2023-12-07 01:12
ahh thank you, I was so confused what was causing this issue plus a few other mods I was using.

**Comment by MattCzyr** [comment] 2024-05-02 01:24
Should be fixed in version 1.3.6.

**Closed by MattCzyr** 2024-05-02 01:24 UTC
Labels: compatibility
